channels:
- conda-forge
dependencies:
- python=3.12.3
- pip<=24.0
- pip:
  - mlflow==2.15.1
  - cloudpickle==3.0.0
  - logging==0.4.9.6
  - numpy==1.26.4
  - psutil==6.0.0
  - scikit-learn==1.4.2
  - scipy==1.13.0
name: mlflow-env
